Improve documentation & some minor formatting
matthieu-m/ghost-cell pull request #9
Opened 2022-05-01 14:46 UTC by konsumlamm

I also changed the `let n = 42;` in the examples to `let n = 12;`, because the examples already use `42` as a value, so I think it would be confusing to use 42 for two different things.

2022-05-10 10:05 UTC, matthieu-m requested changes
Looking good overall.

2022-05-10 10:05 UTC, matthieu-m commented on src/ghost_cursor.rs
> +//! list data structure where each node has an optional previous and next field to point to the previous and next node,
There are two fields (previous and next), hence I believe the plural is correct here.

2022-05-10 12:44 UTC, konsumlamm commented on src/ghost_cursor.rs
> +//! list data structure where each node has an optional previous and next field to point to the previous and next node,
I'm pretty sure my formulation is correct, each node has only a single optional previous field and a single optional next field. The previous formulation is definitely wrong though, "an" is for singular.

2022-05-11 12:40 UTC, matthieu-m commented on src/ghost_cursor.rs
> +//! list data structure where each node has an optional previous and next field to point to the previous and next node,
The previous formulation was definitely mismatching indeed.

I asked for help on Stack Overflow (https://ell.stackexchange.com/questions/314926/is-a-noun-used-for-multiple-adjectives-singular-or-plural), and they pointed out that it's not clear if there's a single optional field (for both previous and next at once) or two with the current formulation.

Instead, the suggestion is to make it clearer there are two fields:

> list data structure where each node has two optional fields, a previous and a next field, to point respectively to the previous and next node,

What do you think?

2022-05-11 16:06 UTC, konsumlamm commented on src/ghost_cursor.rs
> +//! list data structure where each node has an optional previous and next field to point to the previous and next node,
That's a good point, I will use your suggestion.

2022-05-11 16:19 UTC, merged